title: Thien-Khoi N. Phung
headerDescription: Computational Biomechanics
emailName: phung
emailDomain: virginia.edu
department: UVA Department of Biomedical Engineering
twitter: tkphung
github: tkphung
